const fs = require('fs');
const path = require('path');

// Import the old test data
const { testData } = require('../src/data/TestQues');

// Define TestData interface for type safety
interface TestData {
  testId: string;
  title: string;
  description: string;
  duration: number;
  category: string;
  thumbnail?: string;
  passingScore: number;
  questions: Array<{
    id: string;
    question: string;
    options: string[];
    correctAnswer: number;
    explanation?: string;
  }>;
}

// Create the tests directory if it doesn't exist
const testsDir = path.resolve(__dirname, '../src/data/tests');
if (!fs.existsSync(testsDir)) {
  fs.mkdirSync(testsDir, { recursive: true });
}

// Convert old test format to new format
const migrateTest = (oldTest) => {
  return {
    testId: oldTest.testId,
    title: oldTest.title,
    description: oldTest.description,
    duration: oldTest.duration,
    category: oldTest.category,
    thumbnail: oldTest.thumbnail || `https://via.placeholder.com/300x200?text=${encodeURIComponent(oldTest.title)}`,
    passingScore: oldTest.passingScore || 60, // Default passing score
    questions: oldTest.questions.map((q: any) => ({
      id: q.id,
      question: q.question,
      options: q.options,
      correctAnswer: q.correctAnswer,
      explanation: q.explanation || ''
    }))
  };
};

// Ensure the tests directory exists
if (!fs.existsSync(testsDir)) {
  fs.mkdirSync(testsDir, { recursive: true });
}

// Migrate all tests
const migrateAllTests = () => {
  console.log('Starting test migration...');
  
  // Create an index file content
  let indexContent = '// Auto-generated index file for tests\n\n';
  
  testData.forEach((oldTest, index) => {
    try {
      const newTest = migrateTest(oldTest);
      const fileName = `test-${index + 1}.ts`;
      const filePath = path.join(testsDir, fileName);
      
      // Create the test file
      const fileContent = `// This file was auto-generated by migrate-tests.js

const test = ${JSON.stringify(newTest, null, 2)};

module.exports = test;`;
      
      fs.writeFileSync(filePath, fileContent);
      console.log(`Created test file: ${fileName}`);
      
      // Add to index
      indexContent += `const test${index + 1} = require('./test-${index + 1}');
`;
      
    } catch (error) {
      console.error(`Error migrating test ${oldTest.testId || index}:`, error);
    }
  });
  
  // Add exports to index file
  indexContent += '\nconst tests = [\n';
  testData.forEach((_, index) => {
    indexContent += `  test${index + 1},\n`;
  });
  indexContent += `];

module.exports = tests;`;
  
  // Write index file
  fs.writeFileSync(path.join(testsDir, 'index.ts'), indexContent);
  console.log('Created index.ts with all test exports');
  
  console.log('Test migration completed successfully!');
};

// Run the migration
migrateAllTests();
